<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../common.targets" />

  <ItemGroup>
    <PackageReference Include="Franz.Common.Business" />
    <PackageReference Include="Franz.Common.Caching" />
    <PackageReference Include="Franz.Common.Mediator" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Refit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserService.Domain\UserService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Example\Commands\" />
    <Folder Include="Features\Example\Queries\" />
    <Folder Include="Features\Example\Persistence\" />
    <Folder Include="Features\Example\Infrastructure\" />
  </ItemGroup>

</Project>


